workspace: "."
use_gpu: true
num_gpus: 1

inference_image_name: "raphael/lorax"

auto_detect_public_ip: true
request_input_example:
  messages:
  - role: system
    content: You are a helpful assistant.
  - role: user
    content: Who won the world series in 2020?
  - role: assistant
    content: The Los Angeles Dodgers won the World Series in 2020.
  - role: user
    content: Where was it played?

environment_variables:
  #  Launcher Markdown file: `lorax/docs/reference/launcher.md`
  MODEL_ID: ""  # The base model in hugging face OR a local directory.
  QUANTIZE: ""  # Possible Values: bitsandbytes, bitsandbytes-nf4, bitsandbytes-fp4, gptq, awq, eetq, hqq-4bit, hqq-3bit, hqq-2bit
  ADAPTERS_PRELOADED: "" # Model-compatible adapters, the format is "adapter_source_1:adapter_id_1|adapter_source_1:adapter_id_1"

endpoint_api_type: "text2text_llm_openai_chat_completions"
