workspace: "."
use_gpu: true
num_gpus: 1

inference_image_name: "raphael/lorax"

auto_detect_public_ip: true
request_input_example:
  messages:
  - role: system
    content: You are a helpful assistant.
  - role: user
    content: Who won the world series in 2020?
  - role: assistant
    content: The Los Angeles Dodgers won the World Series in 2020.
  - role: user
    content: Where was it played?

environment_variables:
  LORA_BASE_MODEL_ID: "arnavgrg/zephyr-7b-beta-nf4-fp16-upscaled"

endpoint_api_type: "text2text_llm_openai_chat_completions"
